(function(){
  const KEY='moonvale.language';
  const order=['en','pt','es'];
  const base={
    en:{'nav.home':'HOME','nav.ethernia':'ETHERNIA','nav.fantasy':'FANTASY','nav.lore':'LORE LIBRARY','nav.artefacts':'ARTEFACTS','nav.about':'ABOUT','footer.tagline':'Between Stars And Stories','footer.desc':'We are the bridge between worlds and imagination.','footer.navigation':'NAVIGATION','footer.worlds':'WORLDS','footer.archive':'ARCHIVE','footer.connect':'CONNECT','footer.atlas':'Atlas','archive.regions':'Regions','archive.characters':'Characters','archive.relics':'Relics','archive.chronicles':'Chronicles','footer.copy':'© 2025 Moonvale Studio. All rights reserved.','home.tagline':'BETWEEN STARS AND STORIES','home.eth.sub':'The Realm of Light','home.fan.sub':'The Realm of Shadows','home.enter.eth':'ENTER ETHERNIA','home.enter.fan':'ENTER FANTASY','home.scroll':'SCROLL TO DISCOVER','home.featured':'FEATURED COLLECTIONS','home.featured.sub':'Worlds forged in art. Legends brought to life.','home.explore':'EXPLORE THE WORLD','home.explore.sub':'Every place hides a story.','home.open.map':'OPEN INTERACTIVE MAP','home.journey':'CONTINUE THE JOURNEY','home.journey.sub':'More stories. More worlds. More Moonvale.','home.tiktok.eth.desc':'Daily tales from the golden realm','home.tiktok.fan.desc':'Shadows, legends and moonlit stories','home.youtube.desc':'Lore deep dives and world chronicles','home.pinterest.desc':'Visual inspiration from both worlds','music.off':'MUSIC OFF','music.on':'MUSIC ON'},
    pt:{'nav.home':'INÍCIO','nav.ethernia':'ETHERNIA','nav.fantasy':'FANTASY','nav.lore':'BIBLIOTECA DE LORE','nav.artefacts':'ARTEFACTOS','nav.about':'SOBRE','footer.tagline':'Entre Estrelas e Histórias','footer.desc':'Somos a ponte entre mundos e imaginação.','footer.navigation':'NAVEGAÇÃO','footer.worlds':'MUNDOS','footer.archive':'ARQUIVO','footer.connect':'CONTACTO','footer.atlas':'Atlas','archive.regions':'Regiões','archive.characters':'Personagens','archive.relics':'Relíquias','archive.chronicles':'Crónicas','footer.copy':'© 2025 Moonvale Studio. Todos os direitos reservados.','home.tagline':'ENTRE ESTRELAS E HISTÓRIAS','home.eth.sub':'O Reino da Luz','home.fan.sub':'O Reino das Sombras','home.enter.eth':'ENTRAR EM ETHERNIA','home.enter.fan':'ENTRAR EM FANTASY','home.scroll':'DESCE PARA DESCOBRIR','home.featured':'COLEÇÕES EM DESTAQUE','home.featured.sub':'Mundos forjados em arte. Lendas ganham vida.','home.explore':'EXPLORA O MUNDO','home.explore.sub':'Cada lugar esconde uma história.','home.open.map':'ABRIR MAPA INTERATIVO','home.journey':'CONTINUA A JORNADA','home.journey.sub':'Mais histórias. Mais mundos. Mais Moonvale.','home.tiktok.eth.desc':'Contos diários do reino dourado','home.tiktok.fan.desc':'Sombras, lendas e histórias ao luar','home.youtube.desc':'Mergulhos no lore e crónicas dos mundos','home.pinterest.desc':'Inspiração visual dos dois mundos','music.off':'MÚSICA OFF','music.on':'MÚSICA ON'},
    es:{'nav.home':'INICIO','nav.ethernia':'ETHERNIA','nav.fantasy':'FANTASY','nav.lore':'BIBLIOTECA DE LORE','nav.artefacts':'ARTEFACTOS','nav.about':'ACERCA DE','footer.tagline':'Entre Estrellas e Historias','footer.desc':'Somos el puente entre mundos e imaginación.','footer.navigation':'NAVEGACIÓN','footer.worlds':'MUNDOS','footer.archive':'ARCHIVO','footer.connect':'CONTACTO','footer.atlas':'Atlas','archive.regions':'Regiones','archive.characters':'Personajes','archive.relics':'Reliquias','archive.chronicles':'Crónicas','footer.copy':'© 2025 Moonvale Studio. Todos los derechos reservados.','home.tagline':'ENTRE ESTRELLAS E HISTORIAS','home.eth.sub':'El Reino de la Luz','home.fan.sub':'El Reino de las Sombras','home.enter.eth':'ENTRAR EN ETHERNIA','home.enter.fan':'ENTRAR EN FANTASY','home.scroll':'DESPLÁZATE PARA DESCUBRIR','home.featured':'COLECCIONES DESTACADAS','home.featured.sub':'Mundos forjados en arte. Leyendas cobran vida.','home.explore':'EXPLORA EL MUNDO','home.explore.sub':'Cada lugar esconde una historia.','home.open.map':'ABRIR MAPA INTERACTIVO','home.journey':'CONTINÚA EL VIAJE','home.journey.sub':'Más historias. Más mundos. Más Moonvale.','home.tiktok.eth.desc':'Relatos diarios del reino dorado','home.tiktok.fan.desc':'Sombras, leyendas e historias bajo la luna','home.youtube.desc':'Inmersiones en lore y crónicas del mundo','home.pinterest.desc':'Inspiración visual de ambos mundos','music.off':'MÚSICA OFF','music.on':'MÚSICA ON'}
  };
  function lang(){return localStorage.getItem(KEY)||'en'}
  function apply(l){localStorage.setItem(KEY,l);document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=base[l]?.[el.dataset.i18n]||base.en[el.dataset.i18n];if(v)el.textContent=v;});document.querySelectorAll('.nav-lang,.footer-lang-row,.footer-lang').forEach(el=>{el.textContent='PT | EN | ES';el.setAttribute('role','button');el.setAttribute('tabindex','0');});window.dispatchEvent(new CustomEvent('moonvale:languagechange',{detail:{language:l}}));}
  function cycle(){const i=order.indexOf(lang());apply(order[(i+1)%order.length]);}
  document.addEventListener('DOMContentLoaded',()=>{apply(lang());document.querySelectorAll('.nav-lang,.footer-lang-row,.footer-lang').forEach(el=>{el.addEventListener('click',cycle);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();cycle();}});});});
  window.MoonvaleI18n={apply,setLanguage:apply,getLanguage:lang,translations:base};
})();
